Arqsi_P2/IDEIBiblio/Models/Carrinho.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IDEIBiblio.Models
{
    public class Carrinho
    {

        public int CarrinhoID { get; set; }
        public string AnonCarrinhoID { get; set; }
        public int ItemID { get; set; }
        public int Numero { get; set; }
        public DateTime DataC { get; set; }

        public virtual Item Item { get; set; }
    }
}

Arqsi_P2/IDEIBiblio/Controllers/CarrinhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIBiblio.Models;
using IDEIBiblio.ViewModels;

namespace IDEIBiblio.Controllers
{
    public class CarrinhoController : Controller
    {

        IDEIBiblioContext db = new IDEIBiblioContext();
        //
        // GET: /Carrinho/

        public ActionResult Index()
        {
            var cart = CarrinhoCompras.GetCarrinho(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new CarrinhoComprasViewModel
            {
                ItemsCarrinho = cart.GetItemsCarrinho(),
                TotalCarrinho = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }

        // GET: /Carrinho/Adicionar/5
        public ActionResult Adicionar(int id)
        {
            var itemAdicionado = db.Items.Single(item => item.ItemID == id);

            // Add it to the shopping cart
            var carrinho = CarrinhoCompras.GetCarrinho(this.HttpContext);

            carrinho.Adicionar(itemAdicionado);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /Carrinho/Remover/5
        [HttpPost]
        public ActionResult Remover(int id)
        {
            // Remove the item from the cart
            var carrinho = CarrinhoCompras.GetCarrinho(this.HttpContext);

            string nome = db.Carrinhos.Single(item => item.ItemID == id).Item.Titulo;

            // Remove from cart
            int itemCount = carrinho.Remover(id);

            // Display the confirmation message
            var results = new RemoverCarrinhoComprasViewModel
            {
                Mensagem = nome + " foi removido do carrinho.",
                TotalCarrinho = carrinho.GetTotal(),
                CountCarrinho = carrinho.GetNumero(),
                NumItems = itemCount,
                RemoverID = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult Sumario()
        {
            var carrinho = CarrinhoCompras.GetCarrinho(this.HttpContext);

            ViewData["CarrinhoCount"] = carrinho.GetNumero();
            return PartialView("Sumario");
        }

    }
}

Arqsi_P2/IDEIBiblio/Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIBiblio.Models;

namespace IDEIBiblio.Controllers
{
    [Authorize]
    public class CompraController : Controller
    {

        IDEIBiblioContext db = new IDEIBiblioContext();
        Compra compra = null;
        List<IExternalShipping> ShippingPartners = new List<IExternalShipping>()
        {
            new ShippingAll(),
            new LogisticaSA()
        };

        //
        // GET: /Encomendar/Dados
        
        public ActionResult Dados()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Dados(FormCollection formulario)
        {
            compra = new Compra();
            TryUpdateModel(compra);
            try
            {
                compra.Username = User.Identity.Name;
                compra.Data = DateTime.Now;
                db.Compras.Add(compra);
                db.SaveChanges();
                CarrinhoCompras carrinho = CarrinhoCompras.GetCarrinho(this.HttpContext);
                carrinho.CriarCompra(compra);
                return RedirectToAction("Envio", new { id = compra.CompraID });

            }
            catch (Exception ex)
            {
                return View(compra);
            }
        }

        public ActionResult Envio(int id)
        {
            bool valido = db.Compras.Any(o => o.CompraID == id && o.Username == User.Identity.Name);
            if (valido)
            {
                Compra notaEncomenda = db.Compras.Find(id);
                notaEncomenda.ssr = new List<ShippingServiceResults>();
                foreach (IExternalShipping service in ShippingPartners)
                {
                    notaEncomenda.ssr.Add(new ShippingServiceResults()
                    {
                        ShippingService = service.GetNomeServico(),
                        Price = Math.Round(service.GetPrecoPorPagina(notaEncomenda.TotalPag),2)
                    });
                }
                return View(notaEncomenda);
            }
            else
            {
                db.Erros.Add(new Erro() { Descricao = "Page Access Fault -  - " + this.GetType(), When = DateTime.Now, Gravidade = 2 });
                db.SaveChanges();
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult Envio(FormCollection values)
        {
            
            return RedirectToAction("Concluida", new { id = values["hidden"] });
        }




        public ActionResult Concluida(int id)
        {
            bool valido = db.Compras.Any(o => o.CompraID == id && o.Username == User.Identity.Name);
            if (valido)
            {
                return View(id);
            }
            else
            {
                db.Erros.Add(new Erro() { Descricao = "Page Access Fault - " + this.GetType(), When = DateTime.Now, Gravidade = 2 });
                db.SaveChanges();
                return View("Error");
            }
        }

    }
}

Arqsi_P2/IDEIBiblio/Controllers/LojaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using IDEIBiblio.Models;

namespace IDEIBiblio.Controllers
{
    public class LojaController : Controller
    {
        IDEIBiblio.Models.IDEIBiblioContext db = new IDEIBiblio.Models.IDEIBiblioContext();
        //
        // GET: /Loja/
        public ActionResult Index()
        {
            var items = db.Items.ToList();
            return View(items);
        }

        //
        // GET: /Loja/Filtrar?genero=XXX
        public ActionResult Filtrar(string genero)
        {
            if (db.Generoes.Any(g => g.Nome == genero))
            {
                var gen = db.Generoes.SingleOrDefault(g => g.Nome == genero);
                var itemList = db.Items.Where(i => i.GeneroID == gen.GeneroID).ToList();
                ViewBag.genero = gen.Nome;
                return View(itemList);
            }
            db.Erros.Add(new Erro() { Descricao = "Page not found - " + this.GetType(), When = DateTime.Now, Gravidade = 1 });
            db.SaveChanges();
            return View("Error");
        }

        public ActionResult Detalhes(int id)
        {
            if(db.Items.Find(id) == null)
            {
                db.Erros.Add(new Erro() { Descricao = "Page not found - " + this.GetType(), When = DateTime.Now, Gravidade = 1 });
                db.SaveChanges();
                return View("Error");
            }
            Item item = db.Items.Include("Genero").SingleOrDefault(i => i.ItemID == id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        public ActionResult GenerosLateral()
        {
            var generos = db.Generoes.ToList();
            return PartialView(generos);
        }

    }
}

Arqsi_P2/IDEIBiblio/Views/Carrinho/Index.cshtml
@model IDEIBiblio.ViewModels.CarrinhoComprasViewModel
@{
    ViewBag.Title = "Carrinho de Compras";
}
<script src="/Scripts/jquery-2.0.3.min.js"
type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/Carrinho/Remover", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Cart (' + data.CartCount + ')');
                    });
            }
        });
    });
</script>
<h3>
    <label>Conteúdo</label> do seu carrinho:
 </h3>
<p class="button">
    @Html.ActionLink("Checkout", "Dados", "Compra")
</p>
<div id="update-message">
</div>
<table>
    <tr>
        <th>
            Nome Produto
        </th>
        <th>
            Preco (unitário)
        </th>
        <th>
            Quantidade
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.ItemsCarrinho)
    {
        <tr id="row-@item.CarrinhoID">
            <td>
                @Html.ActionLink(item.Item.Titulo, "Detalhes", "Loja", new { id = item.ItemID }, null)
            </td>
            <td>
                @item.Item.Preco
            </td>
            <td id="item-count-@item.CarrinhoID">
                @item.Numero
            </td>
            <td>
                <a href="#" class="RemoveLink" data-id="@item.ItemID">Remover</a>
            </td>
        </tr>
    }
    <tr>
        <td>
            Total
        </td>
        <td>
        </td>
        <td>
        </td>
        <td id="cart-total">
            @Model.TotalCarrinho
        </td>
    </tr>
</table>

Arqsi_P2/IDEIBiblio/Views/Carrinho/Remover.cshtml
@model IDEIBiblio.ViewModels.RemoverCarrinhoComprasViewModel

@{
    ViewBag.Title = "Remover";
}

<h2>Remover</h2>

Arqsi_P2/IDEIBiblio/Views/Carrinho/Sumario.cshtml
@Html.ActionLink("Carrinho (" + ViewData["CarrinhoCount"] + ")", "Index", "Carrinho")